export const Routes = {
    AUTH: {
      BASE: '/v1/auth',
      USERS: '/users',
      USER_LOGIN: '/users/login',
      USER_GOOGLE_LOGIN: '/users/google-login',
      USER_LOGOUT: '/users/logout',
      USER_OTP_SEND: '/users/otp/send',
      USER_OTP_VERIFY: '/users/otp/verify',
      USER_PASSWORD_FORGOT: '/users/password/forgot',
      USER_PASSWORD_RESET: '/users/password/reset',
      USER_PASSWORD_CHANGE: '/users/:id/password/change',
      TOKEN_REFRESH: '/tokens/refresh',
      NEIGHBORS: '/neighbors',
      NEIGHBOR_LOGIN: '/neighbors/login',
      NEIGHBOR_PASSWORD_CHANGE: '/neighbors/:neighborId/password/change',
      ADMIN_LOGIN: '/admin/login',
    },
    ADMIN: {
      BASE: '/v1/admin',
      USERS: '/users',
      NEIGHBORS: '/neighbors',
      TASKS: '/tasks',
      NEIGHBOR_VERIFY: '/neighbors/:id/verify',
      USER_BAN: '/users/:id/ban',
      NEIGHBOR_BAN: '/neighbors/:id/ban',
    },
    NEIGHBORS: {
      BASE: '/v1/neighbors',
      SCHEDULE: '/:neighborId/weekly-schedule',
      AVAILABLE_DAYS:'/:neighborId/available-days',
      SKILLS: '/:neighborId/skills',
      LOCATION: '/:neighborId/location',
      VERIFICATION: '/:neighborId/verification',
      VERIFICATION_STATUS: '/:neighborId/verification/status',
      AVAILABLE_NEIGHBORS: '/available',
      SERVICE_AVAILABILITY: '/service-availability',
      WALLET: '/:neighborId/wallet',
      PAYMENT_HISTORY: '/:neighborId/payments/history',
      TASKS: '/:neighborId/tasks',
    },
    TASKS: {
      BASE: '/v1/tasks',
      CREATE: '/',      
      STATUS: '/:taskId/status',
      VERIFY_CODE: '/:taskId/verify-code',
      COMPLETE: '/:taskId/complete',
      ACCEPT: ':taskId/accept',
  },
  CATEGORY: {
    BASE: '/v1/categories',
    SUB_CATEGORY:'/:categoryId'
    },
    USERS: {
      BASE: '/v1/users',
      TASKS: '/:userId/tasks',
      PROFILE: '/:userId',
      UPDATE_PROFILE: '/:userId',
    },
    MESSAGES: {
      BASE: '/v1/messages',
      SEND: '/',
      CONVERSATION: '/:userId1/:userId2',
    },
    PAYMENTS: {
      BASE: '/v1/payments',
      RECORD: '/',
      WEBHOOK: '/webhook',
      CHECKOUT_SESSION: '/create-checkout-session',
      SESSION_DETAILS: '/session-details/:sessionId',
    },
    HEALTH: '/v1/health',
  };